version: "3.8"

services:
  minio:
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123

  app:
    build: ./app
    container_name: file_management_app
    ports:
      - "5000:5000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    depends_on:
      - minio
      - keycloak
    networks:
      - minionetwork
    volumes:
      - ./app:/app

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak_auth
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    command:
      - start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak:/opt/keycloak/data

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
