version: "3.8"
services:
  nfs:
    image: ghcr.io/normal-computing/nfs-server:latest
    container_name: nfs
    privileged: true
    expose:
      - 2049
      - 111
      - 32765-32767
    environment:
      - SHARED_DIRECTORY=/mnt/data
    volumes:
      - ./nfs-volume:/mnt/data:rw

  app:
    build:
      context: ./app
    container_name: file-management-app
    restart: unless-stopped
    privileged: true
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - nfs
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    command:
      - start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak:/opt/keycloak/data