version: "3.8"
services:
  nfs:
    # image: itsthenetwork/nfs-server-alpine:latest
    image: ghcr.io/normal-computing/nfs-server:latest
    # image: gists/nfs-server
    container_name: nfs
    privileged: true
    expose:
      - 2049
      - 111
      - 32765-32767
    environment:
      - SHARED_DIRECTORY=/mnt/data
    volumes:
      # - ./nfs-volume:/mnt/data:rw
      - ./nfs-volume:/mnt/data:rw
      # - ./nfs-volume:/nfs-share
    #ports:
    #  - 2049:2049

#   nfs-client:
#     image: d3fk/nfs-client:v4
#     container_name: nfs-client
#     privileged: true
#     networks:
#       - internal_network
#     environment:
#       - SERVER=nfs
#       - SHARE=/
#     depends_on:
#       - nfs


  app:
    build:
      context: ./app
    container_name: file-management-app
    restart: unless-stopped
    privileged: true
    # environment:
    #   - NFS_MOUNT=/mnt/nfs
    # volumes:
    #   - nfs-data:/mnt/nfs
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - nfs
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    command:
      - start-dev
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local